<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>br.unb.cic.reach</groupId>
    <artifactId>reach-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <organization>
        <name>Universidade de Brasília</name>
        <url>http://www.cic.unb.br/</url>
    </organization>
    <inceptionYear>2025</inceptionYear>

    <name>Reach :: Parent</name>

    <scm>
        <connection>scm:git:https://github.com/PAMunb/reach-android.git</connection>
        <tag>HEAD</tag>
    </scm>

    <properties>
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>

        <apktool.version>2.12.0</apktool.version> <!--2.10.0 -->
        <flowdroid.version>2.14.1</flowdroid.version> <!--2.10.0 2.14.1 -->
        <gson.version>2.13.1</gson.version> <!-- 2.10.1 -->
        <jcommander.version>1.82</jcommander.version>
        <jgrapht.version>1.5.2</jgrapht.version>
        <logback.version>1.5.18</logback.version> <!-- 1.2.6 -->
        <slf4j.version>2.0.17</slf4j.version> <!-- 1.7.26 -->

        <junit.version>5.13.4</junit.version>

        <maven-clean-plugin.version>3.5.0</maven-clean-plugin.version>
        <maven-resources-plugin.version>3.3.1</maven-resources-plugin.version>
        <maven-compiler-plugin.version>3.14.0</maven-compiler-plugin.version>
        <maven-jar-plugin.version>3.4.2</maven-jar-plugin.version>
        <maven-source-plugin.version>3.3.1</maven-source-plugin.version>
        <maven-assembly-plugin.version>3.7.1</maven-assembly-plugin.version>
        <maven-release-plugin.version>3.1.1</maven-release-plugin.version>
        <maven-surefire-plugin.version>3.5.3</maven-surefire-plugin.version>
        <maven-failsafe-plugin.version>3.5.3</maven-failsafe-plugin.version>

        <jacoco-maven-plugin.version>0.8.13</jacoco-maven-plugin.version>
        <spotbugs-maven-plugin.version>4.7.0.0</spotbugs-maven-plugin.version>
        <fb-contrib.version>7.4.3.sb</fb-contrib.version>
        <versao.findsecbugs-plugin>1.14.0</versao.findsecbugs-plugin>
        <dependency-check-maven.version>7.1.1</dependency-check-maven.version>
        <maven-checkstyle-plugin.version>3.1.2</maven-checkstyle-plugin.version>
        <com.puppycrawl.tools.checkstyle.version>10.3</com.puppycrawl.tools.checkstyle.version>
    </properties>

    <modules>
        <module>reach-core</module>
        <module>reach-apk</module>
        <module>reach-android</module>
        <module>reach-jar</module>
        <module>reach-mop</module>
        <module>reach-main</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>br.unb.cic.reach</groupId>
                <artifactId>core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>br.unb.cic.reach</groupId>
                <artifactId>apk</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>br.unb.cic.reach</groupId>
                <artifactId>android</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>br.unb.cic.reach</groupId>
                <artifactId>jar</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>br.unb.cic.reach</groupId>
                <artifactId>mop</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>de.fraunhofer.sit.sse.flowdroid</groupId>
                <artifactId>soot-infoflow</artifactId>
                <version>${flowdroid.version}</version>
            </dependency>
            <dependency>
                <groupId>de.fraunhofer.sit.sse.flowdroid</groupId>
                <artifactId>soot-infoflow-summaries</artifactId>
                <version>${flowdroid.version}</version>
            </dependency>
            <dependency>
                <groupId>de.fraunhofer.sit.sse.flowdroid</groupId>
                <artifactId>soot-infoflow-android</artifactId>
                <version>${flowdroid.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apktool</groupId>
                <artifactId>apktool-lib</artifactId>
                <version>${apktool.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apktool</groupId>
                <artifactId>apktool-cli</artifactId>
                <version>${apktool.version}</version>
                <optional>true</optional>
            </dependency>

            <dependency>
                <groupId>org.jgrapht</groupId>
                <artifactId>jgrapht-core</artifactId>
                <version>${jgrapht.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-simple</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>${logback.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.code.gson</groupId>
                <artifactId>gson</artifactId>
                <version>${gson.version}</version>
            </dependency>

            <dependency>
                <groupId>com.beust</groupId>
                <artifactId>jcommander</artifactId>
                <version>${jcommander.version}</version>
            </dependency>

            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-api</artifactId>
                <version>${junit.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.maven.surefire</groupId>
                <artifactId>surefire-junit4</artifactId>
                <version>${maven-surefire-plugin.version}</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-clean-plugin</artifactId>
                    <version>${maven-clean-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>${maven-resources-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                        <encoding>${project.build.sourceEncoding}</encoding>
                        <debug>true</debug>
                        <parameters>false</parameters>
                        <verbose>false</verbose>
                        <showWarnings>false</showWarnings>
                        <showDeprecation>false</showDeprecation>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>${maven-jar-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>${maven-source-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <version>${maven-assembly-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-release-plugin</artifactId>
                    <version>${maven-release-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>${jacoco-maven-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven-surefire-plugin.version}</version>
                    <configuration>
                        <runOrder>alphabetical</runOrder>
                        <testFailureIgnore>false</testFailureIgnore>
                        <trimStackTrace>true</trimStackTrace>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>${maven-failsafe-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>com.github.spotbugs</groupId>
                    <artifactId>spotbugs-maven-plugin</artifactId>
                    <version>${versao.spotbugs-maven-plugin}</version>
                    <configuration>
                        <effort>Max</effort>
                        <threshold>Low</threshold>
                        <failOnError>false</failOnError>
                        <debug>false</debug>
                        <includeTests>false</includeTests>
                        <xmlOutput>true</xmlOutput>
                        <htmlOutput>true</htmlOutput>
                        <plugins>
                            <plugin>
                                <groupId>com.mebigfatguy.fb-contrib</groupId>
                                <artifactId>fb-contrib</artifactId>
                                <version>${fb-contrib.version}</version>
                            </plugin>
                            <plugin>
                                <groupId>com.h3xstream.findsecbugs</groupId>
                                <artifactId>findsecbugs-plugin</artifactId>
                                <version>${versao.findsecbugs-plugin}</version>
                            </plugin>
                        </plugins>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <reporting>
        <plugins>
            <plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>${dependency-check-maven.version}</version>
                <reportSets>
                    <reportSet>
                        <reports>
                            <report>aggregate</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
        </plugins>

    </reporting>
</project>